# Generated by Django 6.0.2 on 2026-06-03 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_appointment_appointment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
